### PR TITLE
use inheritIO if showOutput is set

### PR DESCRIPTION
**Pull request by exaV**
inheritIO has different semantics from just printing to the stream gobblers. For example without `pb.inheritIO()` we will not see output from a gradle tasks launched from kscript, that is output will only be visible once the gradle task has finished, not while it is running.

removed redirectStdOut and StdErr parameters because they are unused

### CODE REVIEW

**Comment by exaV** [comment]
I just noticed that my proposed change does not solve the problem. I am a bit at a loss. We are starting a gradle task from kscript, but we see gradle's output on stdout only after the task has finished.

**Comment by holgerbrandl** [comment]
Irrespective of your gradle-issue the change seemed fine, so I've merged it in. 

I'm also contemplating about just moving the few bits used from this kutils artifact over into the kscript repo to keep things more managable.

Could you submit a reproducible example to the kscript tracker? It might be hard to figure out/fix (because only God knows what dark stream magic is happening in gradle) but it might allow other users to contribute ideas as well.

**Comment by exaV** [comment]
Thanks! I must correct myself again, it did in fact solve our issue but only in Gradle 5.0 and above.

**Comment by holgerbrandl** [comment]
So I'd also stall the release until it's more clear what issue it actually solves.

**Pull request merged**
